### ISSUE TITLE
Permission denied - mkdir: cannot create directory 

### ISSUE THREAD

**Issue by cmoulliard** [OpenShiftDemos/nexus#1]
The log of the nexus3 pod reports a permission denied

```
id: cannot find name for user ID 1000050000
mkdir: cannot create directory '../sonatype-work/nexus3/log': Permission denied
mkdir: cannot create directory '../sonatype-work/nexus3/tmp': Permission denied
Warning:  Cannot open log file: ../sonatype-work/nexus3/log/jvm.log
Warning:  Forcing option -XX:LogFile=/tmp/jvm.log
Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file ../sonatype-work/nexus3/log/jvm.log due to No such file or directory

Unable to update instance pid: Unable to create directory /nexus-data/instances
/nexus-data/log/karaf.log (No such file or directory)
Unable to update instance pid: Unable to create directory /nexus-data/instances
```

Commands issued:

```
oc new-project nexus
oc create -f nexus-pv.yaml
oc create -f https://raw.githubusercontent.com/OpenShiftDemos/nexus/master/nexus3-persistent-template.yaml
oc new-app nexus3-persistent -n nexus
```

where nexus-pv.yaml

```
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "nexus-pv"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/pv0001
```
