### ISSUE TITLE
Docker repository name for nexus should be parameterized

### ISSUE THREAD

**Issue by ribeaud** [OpenShiftDemos/nexus#8]
Hi,
**ImageStream** definition looks as following (snippet):

```
...
spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/sonatype/nexus3:${NEXUS_VERSION}
      name: ${NEXUS_VERSION}
...
```

_docker.io/sonatype/nexus3_ should be specified via a parameter as one might want to use its own image.

Another point to consider (applying to my case), it could happen that one already defined an **ImageStream** in the internal **OpenShift** _Docker_ registry. And this is one which will be used by the deployment:

```
...
triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: ${SERVICE_NAME}:${NEXUS_VERSION}
      type: ImageChange
...
```

How could this fit in with the template? In my case, I've removed the section _ImageStream_ from the template.

What do you think?

Kind regards,

christian
